#模板文件，修改内容后不需要上传
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wuanpoint?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #端口
server:
  port: 8080





